name: Check Readme Links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check README Links
        uses: tcort/markdown-link-check@v3.12.2
        with:
          file-path: README.md
          report-style: markdown # Output report as Markdown format

      - name: Prettify and Display Report
        if: failure()
        run: |
          echo "### 🚨 README Link Check Failed 🚨"

          echo "#### ❌ Broken Links:"
          awk '/^- \[x]/{print "* " $2 " (" $3 ")"}' link-check-results.md

          echo ""
          echo "#### ⚠️ Warnings:"
          awk '/^- \[!]/{print "* " $2 " (" $3 ")"}' link-check-results.md

          echo ""
          echo "See 'link-check-results.md' for full details."
