name: Check Readme Links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: tcort/markdown-link-check@v3.12.2 # Directly uses action to check links

      - if: failure()
        run: |
          echo "❌ Invalid links:"
          cat link-check-results.md # Default output file from tcort/markdown-link-check
