name: Check Readme Links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check README Links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose README.md # Limit the scope to README.md, verbose for details
          fail: true # Fail the action if broken links are found

      - name: Prettify and Display Report (if failed)
        if: failure()
        run: |
          echo "### 🚨 README Link Check Failed 🚨"

          echo "#### ❌ Broken Links:"
          awk '/[x]/{print "* " $2 " (" $3 ")"}' lychee/out.md 

          echo ""
          echo "#### ⚠️ Warnings:"
          awk '/[!]/ && !/[x]/{print "* " $2 " (" $3 ")"}' lychee/out.md

          echo ""
          echo "See 'lychee/out.md' for full details."
